### ISSUE TITLE
Публичный выпуск PF2

### ISSUE THREAD

**Issue by unhandled-exception** [unhandled-exception/pf2#45]
PF2 готов для использования в боевых проектах. Можно делать релиз и анонсировать на форуме Парсера. В этом тикете собираем и обсуждаем задачи, которые надо сделать до первого релиза. Чиним явные баги, фичи добавляем только если они ломают совместимость.

Баги:

- [x] Починить монтирование рутового контролера не в корень сайта #43 
- [x] Проверить дженерик для тегирования. Сейчас он явно не работает под pf2.
- [x] В дженерике settings добавить схему и поменять кавычки в запросах
- [x] В авторизации не реализован дефолтный метод для формирования и смены secureToken. При смене пароля авторизационные куки в браузерах не экспайрятся. У меня есть в коммерческом проекте реализация.

Фичи:

- [x] Удалить старую схему вызова экшнов через `@onActionSubaction`. Оставляем только `@/action/subaction`. #46 
- [x] Точный поиск шаблонов #40
- [x] Удалить старую схему постобработчиков postXXX. Оставляем только response<..>. [#47]
- [x] Класс для вывода необработанных исключений #48 

Документация:

- [x] Обновить бутстрап в pf2-secrets-app, поменять /NOTFOUND на catch<http.404>
- [ ] В Ридми pf2-secrets-app добавить про установку приложения. Возможно стоит удалить parser3.cgi и написать куда и как класть Парсер с sql-библиотекой.
- [x] Проверить пример «hello world» на pf2 из ридми. Переделать пути с /classes на /vendor для обнообразия с pf2-secrets-app.
- [ ] Написать минимальную документацию про контролеры, маршрутизацию и мидлваре в docs/controllers.md.
- [ ] Документация на авторизацию или пример проекта. Можно попробовать собрать проектик с моей базовой админкой для пользователей и ролей.
- [x] На страничке PF1 сделать ссылку на PF2.

Отдельный вопрос про версионирование. Базовых вариантов два:

- Версий всего две: master — релиз, develop — свежак. Периодически мерджим develop в master.
- Ввести версионирование. Надо понять как мы живем и как расставляем версии. Например: 2.0.0 — первая версия релиза, 2.0.x — патчики с багфиксами. 2.1.0 — следующий релиз с фичами. В этом случае надо усложнить схему с ветками и использовать, например, гит флоу.

**Comment by gzzz** [comment]
> Удалить старую схему вызова экшнов через @onActionSubaction. Оставляем только @/action/subaction. [Не совсем уверен в этом месте. :)]

C этим согласен, но не совсем согласен с вытекающим «поменять /NOTFOUND на catch<http.404>».

Но поскольку у меня это перекрыто и я пользуюсь своим синтаксисом, то почему бы и нет.
Одна схема лучше смеси двух.

> Отдельный вопрос про версионирование. 

А нельзя ли совместить схемы: ветки master и develop, а при слияния master тегировать версиями?
Ты же сейчас, вроде, так и делаешь?

**Comment by unhandled-exception** [comment]
> C этим согласен, но не совсем согласен с вытекающим «поменять /NOTFOUND на catch<http.404>».

/NOTFOUND оставим. Катч я вставил в пример pf2-secrets-app, чтобы показать что есть альтернативный способ обработки исключений. В hello world из ридми используется /NOTFOUND. Удалять будем только onBlahBlahBalh.

**Comment by unhandled-exception** [comment]
> А нельзя ли совместить схемы: ветки master и develop, а при слияния master тегировать версиями?
> Ты же сейчас, вроде, так и делаешь?

Сейчас просто сливаю ветки по желанию и теги не ставим. Я в pf1 делал условное версионирование: вел ченьжлог и когда накапливалось некоторый объем записей менял версию. Так мы делаем для Парсера. Мне такая схема кажется бессмысленной и в pf1  от нее фактически отказались — держим совместимость насколько возможно и мерджим ветку разработки и релиза как можно чаще. Когда захотелось совсем нового, сделали pf2. :)

Версионирование точно имело бы смысл, если в Парсер было бы принято использовать пакетный менеджер. Пакетник у нас есть, только мы его не используем. Сейчас версионирование добавит нам работы, а пользы особой не видно.

**Comment by unhandled-exception** [comment]
* 5dea9fc Удалил документ pf1_classes.md. #45
* 3d12366 Удалил из контролеров старую схему имен экшнов (onAction). #46

У нас остался один рудимент от старой системы имен — постобработчики (postTEXT, postDEFAULT). Очень хочется их тоже удалить из библиотеки и оставить только `@response<...>`.

**Comment by andreyshpigunov** [comment]
Забавный баг в sql_table.p: в параметре selectОptions буква «О» русская.

**Comment by unhandled-exception** [comment]
> Забавный баг в sql_table.p: в параметре selectОptions буква «О» русская.

Спасибо. Это прямо реальный баг. Поправил. Видиемще и в pf1 пофиксить.

871b730 Поправил ошибку в имени параметра selectOptions в lib/sql/models/sql_table.p@all/__allSelectFieldsExpression. #45

**Comment by gzzz** [comment]
Кстати, 9 мая прошлого года обсуждали переименование и рефакторинг метода `@ifdef`.
Не хочешь по нему пройтись перед релизом, раз широкие массы будут смотреть на код?

**Comment by unhandled-exception** [comment]
Так мы же сделали метод firstdef. Ifdef трогать не будем, потому что массово используется в проектах и смысла его менять нет.

**Comment by unhandled-exception** [comment]
Как раз по итогу майского разговора был тикет #29

**Comment by gzzz** [comment]
> Как раз по итогу майского разговора был тикет #29

Точно, а в открытый тикетах посмотрел и решил, что забылось.

> Так мы же сделали метод firstdef. Ifdef трогать не будем, потому что массово используется в проектах и смысла его менять нет.

Так давай его централизованно переименуем, `@ifdef` → `@firstdef`.
`@ifdef` остался бы алиасом.

**Comment by unhandled-exception** [comment]
Пусть останутся оба. Ифдеф должен быть чуточку эффективнее и пара ifdef/ifcontains выглядит однообразно. Тем более, что я про firstdef вообще не помню, потомоучто никогда не пользуюсь. :)

**Comment by unhandled-exception** [comment]
bf3a492 Поменял вызов парсера в консольных тестах. #45

**Comment by unhandled-exception** [comment]
95e79fa Поправил монтирование рутового контролера не в корень сайта. #43

**Comment by unhandled-exception** [comment]
dc935e5 Убрал старые имена постобработчиков postTYPE, postDEFAULT. #47

Для дефолтного оставил только response<*>, чтобы было аналогично catch.

**Comment by unhandled-exception** [comment]
9319ff4 Поправил обработку хоста в lib/web/controllers.p@pfRequest. Нашел и поправил ошибку в lib/common.p@pfString:parseURL.

**Comment by unhandled-exception** [comment]
Обновления после 10 августа:  
* 3ad0acf Поправил стиль кнопки cancel в виджетах для Бутстрапа 4. #45
* c77eca1 Добавил в csrf-мидлваре параметр с функцией для обработки ошибок. #45
* a7f624c Исправил ошибку в csrf-мидлваре, внесенную в c77eca1. #45
* 56e792f Перенёс поле $request.isAJAX из свойства в констуктор — по аналогии с другими флагами, вычисляющимися одноразово. Дабы не хранить опции конструктора для доступа к ним из геттера.
* eb0b546 Merge pull request #49 from gzzz/develop
* 86e6a32 Добавил +/- для направления сортировки в pfSQLTable в доплнение к asc/desc. #45.
* 2575c5f Поправил расчет времени работы скрипта в pfDebugInfoMiddleware. #45

В некоторых комитах не поставил или перепутал ссылки на тикеты.

**Comment by unhandled-exception** [comment]
* 0e33a93 Поправил ссылки на wkhtmltopdf в api/pdfkit. #45
* 23ddebc Добавил в lib/sql/models/generics/settings/ схему БД, поправил кавычки в запросах. #45
* 480df1e Добавил в авторизацию дефолтный алгоритм генерации хеша пароля и токена. #45

**Comment by unhandled-exception** [comment]
* a7f7d55 Добавил в README.md ссылку на шаблон приложения на pf2. #45
* f2eaaf2 Добавли раскодирование переменной pfRequest.PATH из uri-кодировки. #45
* c44e697 Поменял classes на vendor в примере /hello/world в README.md. #45

**Comment by unhandled-exception** [comment]
* 2852a73 Сделал в pfSQLTable.new корректную работу INSERT IGNORE для разны СУБД. #45
* 05fd9f6 Добавил метод pfSQLTable._allWith, чтобы задавать CTE для запросов select. #45
* 55b11de Восстановил работоспособность дженерика тегирования. #45

**Comment by unhandled-exception** [comment]
Релиз уже много лет публичный. Ни от кого ничего не скрываем
